dist: trusty

language: python
python:
  - "3.5"
  - "3.6"

os:
  - linux

notifications:
  email:
    recipients:
      - asg@airmail.cc
    on_success: never
    on_failure: never

addons:
  apt:
    packages:
    - mpv

install:
  - pip install requests

script:
  - bash start.sh