sudo: required

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux

notifications:
  email:
    recipients:
      - asg@airmail.cc
    on_success: never
    on_failure: never

install:
  - sudo apt-get install python3-requests
  - pip3 install -r requirements.txt

script:
  - sudo python3 base.py